require_relative '../node_modules/react-native/scripts/react_native_pods.rb'
ENV['RCT_NEW_ARCH_ENABLED'] = '1'

install! 'cocoapods', :deterministic_uuids => false


platform :ios, '16.0'
# use_frameworks!
# use_modular_headers!


target 'rn-ios-app' do
  
  # config = use_native_modules!
  # use_react_native!(:path => config[:reactNativePath], hermes_enabled: true)

  use_react_native!(hermes_enabled: true)

  # Manually link the paths to the react native executables and the path to the react native app
#  use_react_native!(path: '../react-native-app/node_modules/react-native', app_path: '../react-native-app', hermes_enabled: true)

  post_install do |installer|
    react_native_post_install(installer)
  end

end


# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == "hermes-engine"
#       target.build_configurations.each do |config|
#         config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = 'NO'
#       end
#     end
#   end
# end
